<?php

/**
 * Implement hook_panels_pane_content_alter().
 *
 * This adds the contextual link to the entity field pane.
 */
function fape_panels_pane_content_alter($content, $pane, $args, $context) {
  // Don't bother with empty panes.
  if (empty($content->content)) {
    return;
  }

  // We also support the node title, author, and created fields specifically.
  elseif (in_array($pane->type, array('node_title', 'node_author', 'node_created'))) {
    $plugin = ctools_get_content_type($pane->type);
    $entity = ctools_content_select_context($plugin, $pane->subtype, $pane->configuration, $context)->data;
    if (node_access('update', $entity)) {
      list($ignore, $field_name) = explode('_', $pane->type);
      $content->admin_links[] = array(
        'title' => t('Edit block'),
        'alt' => t('Edit the data in this block.'),
        'href' => "block/gipo-footer-our-newsletters/edit/en",
        'query' => drupal_get_destination(),
      );
    }
  }
}
