<?php

/**
 * Implement hook_panels_pane_content_alter().
 *
 * This adds the contextual link to the entity field pane.
 */
function fabe_panels_pane_content_alter($content, $pane, $args, $context) {

  if  ($pane->type == 'entity_field' && strpos($pane->subtype,'bean') !== false) {
    $plugin = ctools_get_content_type($pane->type);
    $entity = ctools_content_select_context($plugin, $pane->subtype, $pane->configuration, $context)->data;

    if (entity_access('update', 'bean', $entity)) {
      global $language;
      list($ignore, $field_name) = explode('_', $pane->type);
      $content->admin_links[] = array(
        'title' => t('Edit block'),
        'alt' => t('Edit the data in this block.'),
        'href' => "block/".$entity->delta."/edit/".$language->language,
        'query' => drupal_get_destination(),
      );
    }
  }

}


function fabe_views_pre_view(&$view, &$display_id, &$args) {
    if ($view->base_table=="bean"){
        $view->add_item($view->current_display, 'field', 'bean', 'edit_link', array(
            'label' => '',
            'exclude' => TRUE,
        ), 'edit_link');

        $view->add_item($view->current_display, 'field', 'views', 'contextual_links', array(
            'label' => '',
            'exclude' => false,
            'fields' => array(
                'edit_link' => 'edit_link',
            ),
        ), 'contextual_links');
    }


}
